# aio/Containerfile
#
# Build an all in one Podman, Buildah, Skopeo container
# image from the latest stable version of Podman on the
# Fedoras Updates System.
# https://bodhi.fedoraproject.org/updates/?search=podman
# https://bodhi.fedoraproject.org/updates/?search=buildah
# https://bodhi.fedoraproject.org/updates/?search=skopeo
# This image is intended to be used as-is, or as a base-
# image for development work or use in CI/CD systems.

FROM registry.fedoraproject.org/fedora-minimal:latest

# When building for multiple-architectures in parallel using emulation
# it's really easy for one/more dnf processes to timeout or mis-count
# the minimum download rates.  Bump both to be extremely forgiving of
# an overworked host.
RUN echo -e "\n\n# Added during image build" >> /etc/dnf/dnf.conf && \
    echo -e "minrate=100\ntimeout=60\n" >> /etc/dnf/dnf.conf

RUN microdnf -y makecache && \
    microdnf -y update && \
    microdnf -y install podman buildah skopeo fuse-overlayfs openssh-clients \
        --exclude "container-selinux,qemu-*" && \
    rpm --setcaps shadow-utils 2>/dev/null && \
    microdnf clean all && \
    rm -rf /var/cache /var/log/dnf* /var/log/yum.*

# It's assumed `user` will end up with UID/GID 1000
RUN useradd user && \
    echo -e "user:1:999\nuser:1001:64535" > /etc/subuid && \
    echo -e "user:1:999\nuser:1001:64535" > /etc/subgid

ADD /containers.conf /etc/containers/containers.conf
ADD /user-containers.conf /home/user/.config/containers/containers.conf

RUN mkdir -p /home/user/.local/share/containers && \
    mkdir -p /home/user/.config/containers && \
    chown user:user -R /home/user && \
    chmod 644 /etc/containers/containers.conf

# Copy & modify the defaults to provide reference if runtime changes needed.
# Changes here are required for running with fuse-overlay storage inside container.
RUN sed -e 's|^#mount_program|mount_program|g' \
        -e '/additionalimage.*/a "/var/lib/shared",' \
        -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' \
        /usr/share/containers/storage.conf \
        > /etc/containers/storage.conf

# Setup internal Podman to pass subscriptions down from host to internal container
RUN printf '/run/secrets/etc-pki-entitlement:/run/secrets/etc-pki-entitlement\n/run/secrets/rhsm:/run/secrets/rhsm\n' > /etc/containers/mounts.conf

# Note VOLUME options must always happen after the chown call above
# RUN commands can not modify existing volumes
VOLUME /var/lib/containers
VOLUME /home/user/.local/share/containers

RUN mkdir -p /var/lib/shared/overlay-images \
             /var/lib/shared/overlay-layers \
             /var/lib/shared/vfs-images \
             /var/lib/shared/vfs-layers && \
    touch /var/lib/shared/overlay-images/images.lock && \
    touch /var/lib/shared/overlay-layers/layers.lock && \
    touch /var/lib/shared/vfs-images/images.lock && \
    touch /var/lib/shared/vfs-layers/layers.lock

ENV _CONTAINERS_USERNS_CONFIGURED="" \
    BUILDAH_ISOLATION=chroot
