# skopeo/Containerfile
#
# Build a Skopeo container image from the latest
# stable version of Skopeo on the Fedoras Updates System.
# https://bodhi.fedoraproject.org/updates/?search=skopeo
#
# FLAVOR defaults to stable if unset
#
# FLAVOR=stable    acquires a stable version of Skopeo
#                   from the Fedoras Updates System.
# FLAVOR=testing   acquires a testing version of Skopeo
#                   from the Fedoras Updates System.
# FLAVOR=upstream  acquires a testing version of Skopeo
#                   from the Fedora Copr Buildsystem.
#                   https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/
#
# https://bodhi.fedoraproject.org/updates/?search=skopeo
#
# This image can be used to create a container that runs safely with the
# default set of privileges granted to the container.

FROM registry.fedoraproject.org/fedora:latest

ARG SOURCE_DATE_EPOCH

ARG FLAVOR=stable

ARG UUSER=skopeo

LABEL "io.containers.capabilities"="CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,NET_BIND_SERVICE,SETFCAP,SETGID,SETPCAP,SETUID,SYS_CHROOT"

# When building for multiple-architectures in parallel using emulation
# it's really easy for one/more dnf processes to timeout or mis-count
# the minimum download rates.  Bump both to be extremely forgiving of
# an overworked host.
RUN echo -e "\n\n# Added during image build" >> /etc/dnf/dnf.conf && \
    echo -e "minrate=100\ntimeout=60\n" >> /etc/dnf/dnf.conf

ARG INSTALL_RPMS="skopeo fuse-overlayfs ${SOURCE_DATE_EPOCH:+sqlite}"

# Don't include container-selinux, and remove directories used by dnf that are
# just taking up space.
# TODO: rpm --setcaps... needed due to Fedora (base) image builds
#       being (maybe still?) affected by
#       https://bugzilla.redhat.com/show_bug.cgi?id=1995337#c3
RUN dnf -y makecache && \
    dnf -y update && \
    rpm --setcaps shadow-utils 2>/dev/null && \
    case "${FLAVOR}" in \
      stable) \
        dnf -y install $INSTALL_RPMS \
            --exclude=container-selinux \
      ;; \
      testing) \
        dnf -y install $INSTALL_RPMS \
            --exclude=container-selinux \
            --enablerepo=updates-testing \
      ;; \
      upstream) \
        dnf -y install 'dnf-command(copr)' --enablerepo=updates-testing && \
        dnf -y copr enable rhcontainerbot/podman-next && \
        dnf -y install $INSTALL_RPMS \
            --exclude=container-selinux \
            --enablerepo=updates-testing \
      ;; \
      *) \
        printf "\\nFLAVOR argument must be set and valid, currently: '${FLAVOR}'\\n\\n" 1>&2 && \
        exit 1 \
      ;; \
    esac && \
    dnf clean all && \
    latest=$(rpm -qa --qf '%{buildtime}\n' | sort | tail -n 1) ; \
    echo SOURCE_DATE_EPOCH=${latest} ; \
    if test -n "$SOURCE_DATE_EPOCH" ; then \
        test "$latest" -eq "${SOURCE_DATE_EPOCH}" ; \
        sqlite3 /usr/lib/sysimage/libdnf5/transaction_history.sqlite "UPDATE trans SET dt_begin=$SOURCE_DATE_EPOCH, dt_end=$SOURCE_DATE_EPOCH; PRAGMA journal_mode=DELETE; PRAGMA journal_mode=WAL" ; \
    fi && \
    rm -fv /etc/machine-id /var/lib/systemd/random-seed /var/lib/dnf/repos/*/countme && \
    rm -fv /usr/lib/systemd/profile.d/* && \
    rm -rf /var/cache/*/* /var/log/dnf* /var/log/yum.*

# Copy & modify the system-wide defaults: use fuse-overlay storage.
RUN case "${FLAVOR}" in \
      stable|testing) \
          sed -e 's|^#mount_program|mount_program|g' \
              -e '/^ *additionalimagestores = \[$/a "/var/lib/shared",' \
              -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' \
              /usr/share/containers/storage.conf \
              > /etc/containers/storage.conf ; \
          chmod 644 /etc/containers/storage.conf ; \
      ;; \
      upstream) \
          mkdir -p /etc/containers/storage.rootful.conf.d ; \
          echo '[storage]' > /etc/containers/storage.rootful.conf.d/20-image_build.conf ; \
          echo 'driver = "overlay"' >> /etc/containers/storage.rootful.conf.d/20-image_build.conf ; \
          echo '[storage.options]' >> /etc/containers/storage.rootful.conf.d/20-image_build.conf ; \
          echo 'additionalimagestores = ["/usr/lib/containers/storage","/var/lib/shared"]' >> /etc/containers/storage.rootful.conf.d/20-image_build.conf ; \
          echo '[storage.overlay]' >> /etc/containers/storage.rootful.conf.d/20-image_build.conf ; \
          echo 'mount_program = "/usr/bin/fuse-overlayfs"' >> /etc/containers/storage.rootful.conf.d/20-image_build.conf ; \
          echo 'mountopt= "nodev,fsync=0"' >> /etc/containers/storage.rootful.conf.d/20-image_build.conf ; \
      ;; \
      *) \
        printf "\\nFLAVOR argument must be set and valid, currently: '${FLAVOR}'\\n\\n" 1>&2 && \
        exit 1 \
      ;; \
    esac

# Force `skopeo` to end up with UID/GID 1000, set up some ID mappings, and
# create directories that they might need to be able to write to.
RUN groupadd -g 1000 $UUSER && useradd -u 1000 -g 1000 $UUSER && \
    echo -e "root:1:65535\n$UUSER:1:999\n$UUSER:1001:64535" > /etc/subuid && \
    echo -e "root:1:65535\n$UUSER:1:999\n$UUSER:1001:64535" > /etc/subgid && \
    mkdir -p /home/$UUSER/.local/share/containers && \
    mkdir -p /home/$UUSER/.config/containers && \
    mkdir -p /run/user/1000 && \
    chown -R $UUSER:$UUSER /home/$UUSER /run/user/1000

# Create modified configurations for the unprivileged user.
RUN case "${FLAVOR}" in \
      stable|testing) \
          sed -e 's|^graphroot|# graphroot|g' \
              -e 's|^runroot|# runroot|g' \
              -e '/^ *\"\/usr\/lib\/containers\/storage\" *, *$/d' \
              /etc/containers/storage.conf \
              > /home/$UUSER/.config/containers/storage.conf ; \
          chmod 644 /home/$UUSER/.config/containers/storage.conf ; \
      ;; \
      upstream) \
          mkdir -p /etc/containers/storage.rootless.conf.d ; \
          echo '[storage]' > /etc/containers/storage.rootless.conf.d/20-image_build.conf ; \
          echo 'driver = "overlay"' >> /etc/containers/storage.rootless.conf.d/20-image_build.conf ; \
          echo '[storage.options]' >> /etc/containers/storage.rootless.conf.d/20-image_build.conf ; \
          echo 'additionalimagestores = ["/var/lib/shared"]' >> /etc/containers/storage.rootless.conf.d/20-image_build.conf ; \
          echo '[storage.overlay]' >> /etc/containers/storage.rootless.conf.d/20-image_build.conf ; \
          echo 'mount_program = "/usr/bin/fuse-overlayfs"' >> /etc/containers/storage.rootless.conf.d/20-image_build.conf ; \
          echo 'mountopt= "nodev,fsync=0"' >> /etc/containers/storage.rootless.conf.d/20-image_build.conf ; \
      ;; \
      *) \
        printf "\\nFLAVOR argument must be set and valid, currently: '${FLAVOR}'\\n\\n" 1>&2 && \
        exit 1 \
      ;; \
    esac && \
    chown -R $UUSER:$UUSER /home/$UUSER

# Setup the ability to use additional stores with this container image.
RUN mkdir -p /var/lib/shared/overlay-images \
             /var/lib/shared/overlay-layers \
             /var/lib/shared/vfs-images \
             /var/lib/shared/vfs-layers && \
    touch /var/lib/shared/overlay-images/images.lock && \
    touch /var/lib/shared/overlay-layers/layers.lock && \
    touch /var/lib/shared/vfs-images/images.lock && \
    touch /var/lib/shared/vfs-layers/layers.lock

# Point to the Authorization file
ENV REGISTRY_AUTH_FILE=/tmp/auth.json

# Set the entrypoint
ENTRYPOINT ["/usr/bin/skopeo"]
